import { useEffect, useRef, useState, type ReactNode } from 'react';
import { reference, assetReference, type Json, type Document, type MediaAsset, type SchemaRecord, type Usage } from '@eclosion-tech/grove';
import type { createClient } from '@eclosion-tech/grove/client';
import './references.css';
export type Client = ReturnType<typeof createClient>;
const message = (e: unknown) => e instanceof Error ? e.message : 'Could not complete this request.';
export const title = (value: unknown): string => typeof value === 'string' ? value : value && typeof value === 'object' ? String(Object.values(value)[0] ?? 'Untitled') : 'Untitled';
export function Dialog({ title: heading, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); return () => ref.current?.close(); }, []);
  return <dialog className="grove-dialog" ref={ref} aria-label={heading} onCancel={e => { e.preventDefault(); onClose(); }}><header><h2>{heading}</h2><button type="button" onClick={onClose} aria-label="Close">×</button></header>{children}</dialog>;
}
export function Usages({ client, id, media = false, onOpen }: { client: Client; id: string; media?: boolean; onOpen?: (id: string) => void }) {
  const [rows, setRows] = useState<Usage[]>([]); const [error, setError] = useState(''); const [more, setMore] = useState(false); const [busy, setBusy] = useState(true);
  async function load(append = false) { setBusy(true); try { const next = await (media ? client.mediaWhereUsed(id, append ? rows.length : 0) : client.whereUsed(id, append ? rows.length : 0)); setRows(r => append ? [...r, ...next] : next); setMore(next.length === 50); setError(''); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, [client, id, media]);
  return <div className="grove-usages">{error && <p role="alert">{error}<button type="button" onClick={() => void load()}>Retry</button></p>}{!busy && !error && !rows.length && <p>No current draft or published references.</p>}{rows.map(row => <div key={`${row.sourceId}-${row.channel}-${row.path}`}><strong>{onOpen ? <button type="button" onClick={() => onOpen(row.sourceId)}>{title(row.title)}</button> : title(row.title)}</strong><small>{row.sourceType} · {row.channel === 'published' ? 'Live' : 'Draft'} · {row.path.split('/').filter(Boolean).join(' › ')}</small></div>)}{busy && <p role="status">Loading usage…</p>}{more && <button type="button" disabled={busy} onClick={() => void load(true)}>More usage</button>}</div>;
}
export function ReferenceInput({ client, value, onChange, to = [], multiple = false, image = false, registry }: { client: Client; value: Json | undefined; onChange: (value: Json) => void; to?: string[]; multiple?: boolean; image?: boolean; registry: SchemaRecord }) {
  const [open, setOpen] = useState(false); const [resolved, setResolved] = useState<Record<string, { name: string; status: string }>>({});
  const items = (Array.isArray(value) ? value : value ? [value] : []).filter((v): v is { _ref: string } => !!v && typeof v === 'object' && !Array.isArray(v) && typeof v._ref === 'string');
  const ids = items.map(v => v._ref).join(',');
  useEffect(() => { let active = true; setResolved({}); void Promise.all(items.map(async item => {
    try { if (image) { const asset = await client.getMedia(item._ref); return [item._ref, { name: asset.filename, status: asset.archived ? 'Archived' : `${asset.width} × ${asset.height}` }] as const; }
      const doc = await client.getDocument(item._ref); return [item._ref, { name: title(doc.draft.title ?? doc.id), status: doc.published ? 'Published' : 'Draft · publish before using on a live page' }] as const;
    } catch { return [item._ref, { name: 'Unavailable selection', status: 'Replace this reference' }] as const; }
  })).then(rows => { if (active) setResolved(Object.fromEntries(rows)); }); return () => { active = false; }; }, [client, ids, image]);
  function update(next: Json[]) { onChange(multiple ? next : next[0] ?? null); }
  function choose(item: Document | MediaAsset) { const next = 'draft' in item ? reference(item.id, item.type) : assetReference(item.id); update(multiple ? [...items.filter(i => i._ref !== item.id), next] : [next]); setOpen(false); }
  return <div className="grove-reference">{items.map((item, index) => <div className="grove-selection" key={item._ref}>{image && <img src={client.mediaContentUrl(item._ref)} alt=""/>}<div><strong>{resolved[item._ref]?.name ?? 'Loading selection…'}</strong><small>{resolved[item._ref]?.status}</small></div>{multiple && <><button type="button" disabled={index === 0} aria-label="Move selection up" onClick={() => { const next = [...items]; [next[index - 1], next[index]] = [next[index]!, next[index - 1]!]; update(next); }}>↑</button><button type="button" disabled={index === items.length - 1} aria-label="Move selection down" onClick={() => { const next = [...items]; [next[index + 1], next[index]] = [next[index]!, next[index + 1]!]; update(next); }}>↓</button></>}<button type="button" aria-label={`Remove ${resolved[item._ref]?.name ?? 'selection'}`} onClick={() => update(items.filter((_, i) => i !== index))}>×</button></div>)}<button type="button" onClick={() => setOpen(true)}>{items.length && !multiple ? 'Change' : 'Choose'} {image ? 'image' : 'record'}</button>{open && <Dialog title={image ? 'Choose an image' : 'Choose a record'} onClose={() => setOpen(false)}>{image ? <MediaBrowser client={client} registry={registry} onChoose={choose}/> : <RecordBrowser client={client} to={to} registry={registry} onChoose={choose}/>}</Dialog>}</div>;
}
function RecordBrowser({ client, to, registry, onChoose }: { client: Client; to: string[]; registry: SchemaRecord; onChoose: (doc: Document) => void }) {
  const [type, setType] = useState(to[0] ?? ''); const [search, setSearch] = useState(''); const [rows, setRows] = useState<Document[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(true); const [more, setMore] = useState(false);
  useEffect(() => { let active = true; setBusy(true); setRows([]); setError(''); const timer = setTimeout(() => { void client.listDocuments({ type, search, limit: 50 }).then(rows => { if (active) { setRows(rows); setMore(rows.length === 50); } }).catch(e => { if (active) setError(message(e)); }).finally(() => { if (active) setBusy(false); }); }, 200); return () => { active = false; clearTimeout(timer); }; }, [client, type, search]);
  async function loadMore() { setBusy(true); try { const next = await client.listDocuments({ type, search, after: rows.at(-1)?.id, limit: 50 }); setRows([...rows, ...next]); setMore(next.length === 50); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  return <div className="grove-browser"><label>Search records<input autoFocus value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by title…"/></label>{to.length > 1 && <label>Collection<select value={type} onChange={e => setType(e.target.value)}>{to.map(t => <option key={t} value={t}>{registry.definition.types.find(c => c.name === t)?.label ?? t}</option>)}</select></label>}{error && <p role="alert">{error}</p>}<div className="grove-records">{rows.map(doc => <button type="button" key={doc.id} onClick={() => onChoose(doc)}><strong>{title(doc.draft.title ?? doc.id)}</strong><small>{registry.definition.types.find(c => c.name === doc.type)?.label ?? doc.type} · {doc.published ? 'Published' : 'Draft'}</small></button>)}</div>{busy ? <p role="status">Searching…</p> : !rows.length && !error ? <p>No records found. Create one in its collection first.</p> : null}{more && <button type="button" disabled={busy} onClick={() => void loadMore()}>More records</button>}</div>;
}
export function MediaBrowser({ client, registry, onChoose, onOpen }: { client: Client; registry: SchemaRecord; onChoose?: (asset: MediaAsset) => void; onOpen?: (id: string) => void }) {
  const [search, setSearch] = useState(''); const [archived, setArchived] = useState(false); const [rows, setRows] = useState<MediaAsset[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [more, setMore] = useState(false); const [refresh, setRefresh] = useState(0); const [selected, setSelected] = useState<MediaAsset | null>(null);
  useEffect(() => { let active = true; setBusy(true); setError(''); setRows([]); const timer = setTimeout(() => { void client.listMedia({ search, archived, limit: 40 }).then(rows => { if (active) { setRows(rows); setMore(rows.length === 40); } }).catch(e => { if (active) setError(message(e)); }).finally(() => { if (active) setBusy(false); }); }, 200); return () => { active = false; clearTimeout(timer); }; }, [client, search, archived, refresh]);
  async function upload(file?: File) { if (!file) return; setBusy(true); setError(''); try { const asset = await client.uploadMedia(file, file.name); setSelected(asset); setRefresh(v => v + 1); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  async function loadMore() { setBusy(true); try { const next = await client.listMedia({ search, archived, after: rows.at(-1)?.id, limit: 40 }); setRows([...rows, ...next]); setMore(next.length === 40); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  return <div className="grove-browser"><div className="grove-media-tools"><label>Find an image<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search filenames…"/></label><label>Upload image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e => { void upload(e.target.files?.[0]); e.target.value = ''; }}/></label></div><small>JPEG, PNG, or WebP · up to 10 MB and 25 megapixels</small>{!onChoose && <label className="grove-check"><input type="checkbox" checked={archived} onChange={e => setArchived(e.target.checked)}/>Show archived images</label>}{error && <p role="alert">{error}</p>}<div className="grove-media-grid">{rows.map(asset => <button type="button" key={asset.id} onClick={() => setSelected(asset)}><img src={client.mediaContentUrl(asset.id)} alt="" loading="lazy"/><strong>{asset.filename}</strong><small>{asset.width} × {asset.height}</small></button>)}</div>{busy ? <p role="status">Loading images…</p> : !rows.length && !error ? <p>{search ? 'No matching images.' : archived ? 'No archived images.' : 'Upload your first image to start your library.'}</p> : null}{more && <button type="button" disabled={busy} onClick={() => void loadMore()}>More images</button>}{selected && <MediaDetails key={`${selected.id}-${selected.revision}`} client={client} asset={selected} registry={registry} onClose={() => setSelected(null)} onSaved={asset => { setSelected(asset); setRefresh(v => v + 1); }} onChoose={onChoose} onOpen={onOpen}/>}</div>;
}
function MediaDetails({ client, asset, registry, onClose, onSaved, onChoose, onOpen }: { client: Client; asset: MediaAsset; registry: SchemaRecord; onClose: () => void; onSaved: (asset: MediaAsset) => void; onChoose?: (asset: MediaAsset) => void; onOpen?: (id: string) => void }) {
  const [alt, setAlt] = useState(asset.alt); const [caption, setCaption] = useState(asset.caption); const [point, setPoint] = useState(asset.focalPoint); const [locale, setLocale] = useState(registry.definition.defaultLocale); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const dirty = JSON.stringify([alt, caption, point]) !== JSON.stringify([asset.alt, asset.caption, asset.focalPoint]);
  useEffect(() => { const leave = (e: BeforeUnloadEvent) => { if (dirty) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', leave); return () => window.removeEventListener('beforeunload', leave); }, [dirty]);
  function close() { if (!busy && (!dirty || window.confirm('Discard unsaved image details?'))) onClose(); }
  async function save(choose = false) { setBusy(true); setError(''); try { const next = dirty ? await client.updateMedia(asset.id, { expectedRevision: asset.revision, alt, caption, focalPoint: point }) : asset; if (choose && onChoose) onChoose(next); else onSaved(next); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  return <Dialog title={asset.filename} onClose={close}><div className="grove-media-detail"><img src={client.mediaContentUrl(asset.id)} alt={alt[locale] ?? ''} style={{ objectPosition: `${point.x * 100}% ${point.y * 100}%` }}/><small>{asset.width} × {asset.height} · {Math.ceil(asset.bytes / 1024)} KB · {asset.archived ? 'Archived' : 'Available'}</small></div><fieldset disabled={busy}><label>Language<select value={locale} onChange={e => setLocale(e.target.value)}>{registry.definition.locales.map(l => <option key={l}>{l}</option>)}</select></label><label>Alternative text<input value={alt[locale] ?? ''} maxLength={2000} onChange={e => setAlt({ ...alt, [locale]: e.target.value })}/><small>Describe the image for someone who cannot see it. Leave empty for decorative images.</small></label><label>Caption<textarea value={caption[locale] ?? ''} maxLength={2000} onChange={e => setCaption({ ...caption, [locale]: e.target.value })}/></label><div className="grove-media-tools">{(['x', 'y'] as const).map(axis => <label key={axis}>Focal point · {axis === 'x' ? 'horizontal' : 'vertical'}<input type="range" min="0" max="1" step="0.01" value={point[axis]} onChange={e => setPoint({ ...point, [axis]: Number(e.target.value) })}/></label>)}</div><small>These details are shared wherever this image is used. Saving updates them immediately.</small><div className="grove-actions"><button type="button" disabled={!dirty} onClick={() => void save()}>Save details</button>{onChoose && !asset.archived && <button type="button" onClick={() => void save(true)}>Use this image</button>}{!onChoose && <button type="button" disabled={dirty} onClick={() => { setBusy(true); setError(''); void (asset.archived ? client.restoreMedia(asset.id, asset.revision) : client.archiveMedia(asset.id, asset.revision)).then(onSaved).catch(e => setError(message(e))).finally(() => setBusy(false)); }}>{asset.archived ? 'Restore image' : 'Archive image'}</button>}</div></fieldset>{error && <p role="alert">{error}<button type="button" onClick={() => { if (!dirty || window.confirm('Discard your edits and load the latest image details?')) void client.getMedia(asset.id).then(onSaved).catch(e => setError(message(e))); }}>Reload details</button></p>}<h3>Where it’s used</h3><Usages client={client} id={asset.id} media onOpen={onOpen ? id => { if (!dirty || window.confirm('Discard unsaved image details?')) onOpen(id); } : undefined}/></Dialog>;
}
