import { createEmailConfig } from '@eclosion-tech/grove-email/editor';
import { useEffect, useMemo, useState, useSyncExternalStore, useCallback } from 'react';
import { Puck, type Data } from '@puckeditor/core';
import { createClient } from '@eclosion-tech/grove/client';
import { EditingSession } from '@eclosion-tech/grove/editing';
import type { Document, Json, SchemaRecord } from '@eclosion-tech/grove';
import { starter, validateEmail, type EmailDocument } from '@eclosion-tech/grove-email';
import { ReferenceInput, type Client } from '../../shared/References.js';
import { parseCsv } from './email-csv.js';
import '@puckeditor/core/no-external.css';
import './email.css';

type Settings = { connected: boolean; from: string; fromName: string; canSend: boolean; canManageAudiences: boolean };
type Api = (path: string, body?: unknown) => Promise<any>;
const message = (e: unknown) => e instanceof Error ? e.message : 'Could not complete this action.';
export function EmailWorkspace({ client, registry, csrf, registerGuard }: { client: ReturnType<typeof createClient>; registry: SchemaRecord; csrf: string; registerGuard: (guard: () => Promise<boolean>) => () => void }) {
  const api = useCallback<Api>(async (path, body) => {
    const response = await fetch(`/email/${path}`, { credentials: 'same-origin', method: body === undefined ? 'GET' : 'POST', headers: { 'Content-Type': 'application/json', 'X-Grove-CSRF': csrf }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    const value = await response.json(); if (!response.ok) throw new Error(value.error?.message ?? value.error ?? 'Email request failed'); return value;
  }, [csrf]);
  const [settings, setSettings] = useState<Settings | null>(null); const [tab, setTab] = useState('drafts');
  const [cancelId, setCancelId] = useState('');
  const [drafts, setDrafts] = useState<Document[]>([]); const [selected, setSelected] = useState<Document | null>(null);
  const [audiences, setAudiences] = useState<any[]>([]); const [results, setResults] = useState<any[]>([]);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  async function load() { try {
    const s = await api('config'); setSettings(s); setDrafts(await client.listDocuments({ type: 'email', limit: 100 }));
    if (s.connected) { const [a, r] = await Promise.all([api('audiences'), api('campaigns')]); setAudiences(a); setResults(r); }
    setError('');
  } catch (e) { setError(message(e)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [client, api]);
  async function create(kind: string, source?: Document) { setBusy(true); try {
    const data = source ? { ...source.draft, title: `${source.draft.title} — copy` } : starter(kind, settings?.fromName);
    const doc = await client.saveDocument(crypto.randomUUID(), { type: 'email', expectedRevision: 0, expectedSchemaVersion: registry.version, data: JSON.parse(JSON.stringify(data)) });
    setSelected(doc);
  } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  if (selected && settings) return <EmailEditor key={selected.id} doc={selected} registry={registry} client={client} api={api} settings={settings} audiences={audiences} registerGuard={registerGuard} onBack={() => { setSelected(null); void load(); }}/>;
  return <section className="content-view email-workspace"><div className="page-heading"><div><span className="eyebrow">A NOTE FROM YOU</span><h1>Email</h1><p>Good news, thoughtfully delivered.</p></div><button onClick={() => void load()} disabled={loading}>Refresh</button></div>
    <nav className="email-tabs" aria-label="Email sections">{['drafts', 'audiences', 'results'].map(t => <button key={t} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)}>{t === 'drafts' ? 'Newsletters & templates' : t[0]!.toUpperCase() + t.slice(1)}</button>)}</nav>
    {error && <p className="error" role="alert">{error}</p>}
    {settings && !settings.connected && <p className="notice">Your writing workspace is ready. Email delivery hasn’t been connected yet; drafts and previews work now.</p>}
    {loading ? <p role="status">Opening your email workspace…</p> : tab === 'drafts' ? <><div className="email-starters">{[['newsletter', 'Newsletter', 'A little of everything.'], ['class', 'Class announcement', 'Invite them to learn something new.'], ['event', 'Event reminder', 'Save a place in their calendar.']].map(([id, title, description]) => <button disabled={busy} key={id} onClick={() => void create(id!)}><span>START WITH A TEMPLATE</span><strong>{title}</strong><small>{description}</small><b>Make it yours ↗</b></button>)}</div><h2>Your drafts</h2>{!drafts.length && <p className="email-muted">Choose a starting template above to write your first email.</p>}<div className="email-drafts">{drafts.map(doc => <article key={doc.id}><button onClick={() => setSelected(doc)}><strong>{String(doc.draft.title)}</strong><span>{String(doc.draft.subject || 'Add a subject line')}</span><small>Edited {new Date(doc.updatedAt).toLocaleString()} · Revision {doc.revision}</small></button><button disabled={busy} onClick={() => void create('', doc)}>Use as template</button></article>)}</div></> : tab === 'audiences' ? <Audiences api={api} rows={audiences} settings={settings} reload={load}/> : <><p className="email-muted">Opens and clicks are estimates; privacy features and automated scanners can affect them.</p>{!results.length ? <p>No broadcasts yet.</p> : <div className="table-wrap"><table><thead><tr><th>Broadcast</th><th>Status</th><th>Recipients</th><th>Accepted</th><th>Blocked / failed</th><th>Opens / clicks</th></tr></thead><tbody>{results.map(r => <tr key={r.id}><td><strong>{r.name}</strong><small>{r.subject}</small>{r.scheduledAt && <small>{new Date(r.scheduledAt).toLocaleString()}</small>}</td><td>{r.status === 'sent' ? 'Completed' : r.status === 'scheduled' ? 'Scheduled' : r.status === 'cancelled' ? 'Cancelled' : 'Sending'}</td><td>{r.total}</td><td>{['sent', 'delivered', 'opened', 'clicked'].reduce((n, key) => n + (r.counts[key] ?? 0), 0)}</td><td>{(r.counts.blocked ?? 0) + (r.counts.failed ?? 0) + (r.counts.bounced ?? 0)}</td><td>{r.opens} / {r.clicks}<small>{r.unsubscribes} unsubscribed</small>{r.status === 'scheduled' && settings?.canSend && <button disabled={busy} onClick={async () => { if (cancelId !== r.id) { setCancelId(r.id); return; } setBusy(true); try { await api(`campaigns/${r.id}/cancel`, {}); setCancelId(''); await load(); } catch (e) { setError(message(e)); } finally { setBusy(false); } }}>{cancelId === r.id ? 'Confirm cancellation' : 'Cancel scheduled send'}</button>}</td></tr>)}</tbody></table></div>}</>}
  </section>;
}
function EmailEditor({ doc, registry, client, api, settings, audiences, registerGuard, onBack }: { doc: Document; registry: SchemaRecord; client: Client; api: Api; settings: Settings; audiences: any[]; registerGuard: (guard: () => Promise<boolean>) => () => void; onBack: () => void }) {
  const [session] = useState(() => new EditingSession(client, doc, registry)); const state = useSyncExternalStore(session.subscribe, session.getSnapshot);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [view, setView] = useState('compose');
  const [html, setHtml] = useState(''); const [width, setWidth] = useState(640); const [listId, setListId] = useState(''); const [scheduled, setScheduled] = useState('');
  const [testTo, setTestTo] = useState(''); const [review, setReview] = useState<any>(null); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false);
  const [history, setHistory] = useState<any[] | null>(null);
  useEffect(() => { session.start(); const unregister = registerGuard(async () => !!await session.flush()); const leave = (e: BeforeUnloadEvent) => { if (session.unsettled) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', leave); return () => { session.stop(); unregister(); window.removeEventListener('beforeunload', leave); }; }, [session, registerGuard]);
  const color = (state.data.layout as unknown as EmailDocument['layout']).root.props.color;
  const config = useMemo(() => createEmailConfig({ imageField: ({ value, onChange }) => <ReferenceInput client={client} registry={registry} image value={value} onChange={onChange}/>, imageUrl: id => client.mediaContentUrl(id), color }), [client, registry, color]);
  const data = useMemo(() => session.getSnapshot().data.layout as unknown as Data, [doc.id, view]);
  function change(layout: Data) { try { const clean = JSON.parse(JSON.stringify(layout)); validateEmail({ ...session.getSnapshot().data, layout: clean }); session.setInvalid('layout', false); session.setField('layout', clean); setError(''); setReview(null); } catch (e) { session.setInvalid('layout', true); setError(message(e)); } }
  async function action(kind: 'preview' | 'review' | 'test') { setBusy(true); setError(''); try {
    const saved = await session.flush(); if (!saved) throw new Error('Resolve the draft save issue first.');
    const result = await api(kind, { documentId: saved.id, revision: saved.revision, listId, ...(scheduled ? { scheduledAt: new Date(scheduled).toISOString() } : {}), ...(kind === 'test' ? { to: testTo } : {}) });
    if (kind === 'test') setNotice(`Test email queued for ${testTo}.`); else { setHtml(result.html); setView(kind); setReview(kind === 'review' ? result : null); }
  } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  function exportDraft() { const url = URL.createObjectURL(new Blob([JSON.stringify(state.data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `${doc.id}.json`; a.click(); URL.revokeObjectURL(url); }
  return <section className="email-editor"><div className="email-toolbar"><button disabled={busy} onClick={() => void session.flush().then(saved => { if (saved) onBack(); })}>← All emails</button><span role="status">{state.invalid.length ? 'Check your email' : state.status === 'saved' ? 'All changes saved' : state.status === 'saving' ? 'Saving…' : state.status === 'conflict' ? 'Save conflict' : 'Unsaved changes'}</span><button onClick={() => void session.flush()}>Save draft</button><button onClick={exportDraft}>Export JSON</button><button onClick={() => void client.history(doc.id).then(setHistory).catch(e => setError(message(e)))}>History</button></div>
    {(error || state.error) && <p className="error" role="alert">{error || state.error}{state.status === 'conflict' && <><br/>Your local changes are preserved. Export your draft before loading the latest saved version.<button onClick={exportDraft}>Export my draft</button><button onClick={() => location.reload()}>Reload saved version</button></>}</p>}{notice && <p className="notice" role="status">{notice}</p>}
    <div className="email-details">{[['title', 'Internal name'], ['subject', 'Subject line'], ['previewText', 'Inbox preview']].map(([key, label]) => <label key={key}>{label}<input value={String(state.data[key!] ?? '')} maxLength={key === 'subject' ? 500 : key === 'previewText' ? 200 : 255} disabled={busy || state.status === 'conflict'} onChange={e => { session.setField(key!, e.target.value); setReview(null); }}/></label>)}</div>
    <nav className="email-tabs"><button className={view === 'compose' ? 'selected' : ''} onClick={() => { setView('compose'); setReview(null); }}>Compose</button><button disabled={busy} className={view === 'preview' ? 'selected' : ''} onClick={() => void action('preview')}>Preview</button><span className="email-muted">Personalize with {'{{subscriber.name}}'} or {'{{subscriber.email}}'}.</span></nav>
    {view === 'compose' ? <div><div className={busy || state.status === 'conflict' ? 'email-puck locked' : 'email-puck'}><Puck config={config} data={data} onChange={change} iframe={{ enabled: true }} viewports={[{ width: 600, height: 'auto', label: 'Email' }, { width: 375, height: 'auto', label: 'Phone' }]} fieldTransforms={{ richtext: ({ value }) => value }} overrides={{ header: () => <div className="email-canvas-title">Your email · drag blocks to arrange</div> }}/></div></div> : <div className="email-preview"><div className="email-preview-controls"><button onClick={() => setWidth(640)}>Desktop</button><button onClick={() => setWidth(375)}>Phone</button><span>Rendered email preview</span></div><iframe sandbox="" srcDoc={html} title="Rendered email preview" style={{ width, maxWidth: '100%', height: 740 }}/></div>}
    <div className="email-send-panel"><div><h2>Make sure it feels right.</h2><p>Send a test to yourself before sharing it with your audience.</p><label>Test recipient<input type="email" value={testTo} onChange={e => setTestTo(e.target.value)} placeholder="you@example.com"/></label><button disabled={busy || !settings.connected || !settings.canSend || !testTo} onClick={() => void action('test')}>Send test email</button></div><div><h2>Ready to share?</h2><label>Audience<select value={listId} onChange={e => { setListId(e.target.value); setReview(null); }}><option value="">Choose an audience</option>{audiences.map(a => <option key={a.id} value={a.id}>{a.name} · {a.active} active</option>)}</select></label><label>Send time (your local timezone)<input type="datetime-local" value={scheduled} onChange={e => { setScheduled(e.target.value); setReview(null); }}/><small>Leave empty to send after confirmation.</small></label><button className="primary" disabled={busy || !settings.connected || !settings.canSend || !listId || sent} onClick={() => void action('review')}>Review broadcast →</button></div></div>
    {review && <div className="email-review" role="region" aria-label="Review broadcast"><span className="eyebrow">ONE LAST LOOK</span><h2>{review.summary.subject}</h2><p>From {review.summary.from}</p><p><strong>{review.summary.recipients} recipients</strong> in {review.summary.audience}</p><p>{review.summary.scheduledAt ? `Scheduled for ${new Date(review.summary.scheduledAt).toLocaleString()}` : 'Send as soon as you confirm.'} · Saved revision {review.summary.revision}</p><p>Later edits to this draft will not change this broadcast.</p><button className="primary" disabled={busy || sent} onClick={async () => { setBusy(true); setError(''); try { const result = await api('send', { review: review.review }); setSent(true); setNotice(`Broadcast ${result.replayed ? 'was already' : 'is'} queued for ${result.recipients} recipients. View progress in Results.`); } catch (e) { setError(message(e)); } finally { setBusy(false); } }}>{sent ? 'Broadcast queued' : busy ? 'Submitting…' : scheduled ? 'Confirm schedule' : `Send to ${review.summary.recipients} recipients`}</button></div>}
    {history && <div className="email-history"><h2>Draft history</h2><p>Restoring creates a new draft revision. Sent broadcasts stay unchanged.</p><button onClick={() => setHistory(null)}>Close history</button>{history.map(h => <div key={h.revision}><span>Revision {h.revision} · {h.action} · {h.actorId}</span><button disabled={busy} onClick={async () => { setBusy(true); try { const restored = await session.action('restore', h.revision); if (restored) location.reload(); } finally { setBusy(false); } }}>Restore as draft</button></div>)}</div>}
  </section>;
}
function Audiences({ api, rows, settings, reload }: { api: Api; rows: any[]; settings: Settings | null; reload: () => Promise<void> }) {
  const [name, setName] = useState(''); const [listId, setListId] = useState(''); const [table, setTable] = useState<string[][]>([]); const [fileName, setFileName] = useState('');
  const [emailCol, setEmailCol] = useState(0); const [nameCol, setNameCol] = useState(-1); const [statusCol, setStatusCol] = useState(-1); const [consent, setConsent] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [members, setMembers] = useState<any[]>([]); const [more, setMore] = useState(false);
  async function loadMembers(id: string, after?: string) { try { const next = await api(`audiences/${id}${after ? `?after=${after}` : ''}`); setMembers(m => after ? [...m, ...next] : next); setMore(next.length === 100); } catch (e) { setError(message(e)); } }
  return <div className="email-audiences">{error && <p className="error" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}<div className="email-audience-cards">{rows.map(r => <button key={r.id} onClick={() => { setListId(r.id); void loadMembers(r.id); }}><strong>{r.name}</strong><span>{r.active} active · {r.total} total</span></button>)}</div><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { const list = await api('audiences', { name }); setListId(list.id); setName(''); await reload(); } catch (e) { setError(message(e)); } finally { setBusy(false); } }}><label>New audience name<input value={name} onChange={e => setName(e.target.value)} required/></label><button disabled={busy || !settings?.connected || !settings.canManageAudiences}>Create audience</button></form>
    <h2>Bring your subscribers</h2><p>Import a CSV from Kit or Mailchimp. Existing unsubscribes, bounces, and complaints stay suppressed.</p><label>Import into<select value={listId} onChange={e => { setListId(e.target.value); setMembers([]); }}>{!listId && <option value="">Choose an audience</option>}{rows.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>CSV file<input type="file" accept=".csv,text/csv" onChange={async e => { try { const file = e.target.files?.[0]; if (!file) return; if (file.size > 5_000_000) throw new Error('Choose a CSV smaller than 5 MB'); const parsed = parseCsv(await file.text()); if (parsed.length > 10001) throw new Error('Import up to 10,000 subscribers at a time'); setTable(parsed); setFileName(file.name); setConsent(false); const headers = parsed[0] ?? []; setEmailCol(Math.max(0, headers.findIndex(h => /email/i.test(h)))); setNameCol(headers.findIndex(h => /^(first.?name|name)$/i.test(h))); setStatusCol(headers.findIndex(h => /status|state/i.test(h))); setError(''); } catch (e) { setError(message(e)); } }}/></label>
    {table.length > 1 && <><p>{table.length - 1} rows ready to map.</p><div className="email-details">{[['Email', emailCol, setEmailCol], ['Name', nameCol, setNameCol], ['Status', statusCol, setStatusCol]].map(([label, value, setter]) => <label key={String(label)}>{String(label)} column<select value={value as number} onChange={e => (setter as (n: number) => void)(Number(e.target.value))}>{label !== 'Email' && <option value={-1}>Not provided</option>}{table[0]!.map((h, i) => <option key={i} value={i}>{h}</option>)}</select></label>)}</div><p>Supported statuses: active/subscribed, unsubscribed/cancelled, bounced/cleaned, complained. A missing status means active.</p><label className="email-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/>I confirm these contacts can receive our broadcasts and that this export includes their current subscription status.</label><button disabled={busy || !consent || !listId || !settings?.canManageAudiences} className="primary" onClick={async () => { setBusy(true); setError(''); try {
      const mapping: Record<string, string> = { active: 'active', subscribed: 'active', unsubscribed: 'unsubscribed', cancelled: 'unsubscribed', canceled: 'unsubscribed', bounced: 'bounced', cleaned: 'bounced', complained: 'complained' };
      const input = table.slice(1).map((row, i) => { const value = statusCol < 0 ? 'active' : (row[statusCol] ?? '').trim().toLowerCase(); const status = mapping[value]; if (!status) throw new Error(`Unknown status on row ${i + 2}: ${value || '(empty)'}`); return { email: row[emailCol]?.trim(), name: nameCol < 0 ? undefined : row[nameCol]?.trim(), status }; });
      // Validate all rows before the first batch is committed.
      if (input.some(r => !r.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email))) throw new Error('Some rows have an invalid email address. Fix the CSV before importing.');
      let inserted = 0, preserved = 0; for (let i = 0; i < input.length; i += 1000) { const r = await api(`audiences/${listId}/import`, { rows: input.slice(i, i + 1000), consentConfirmed: true, source: fileName.slice(0, 100) }); inserted += r.inserted; preserved += r.preserved; }
      setNotice(`Import complete: ${inserted} new contacts; ${preserved} existing contacts preserved.`); setTable([]); await reload(); await loadMembers(listId);
    } catch (e) { setError(`${message(e)} Completed batches are preserved; retrying the same import will not reactivate or duplicate contacts.`); } finally { setBusy(false); } }}>{busy ? 'Importing…' : 'Import subscribers'}</button></>}
    {!!members.length && <div className="table-wrap"><table><thead><tr><th>Email</th><th>Name</th><th>Status</th></tr></thead><tbody>{members.map(m => <tr key={m.id}><td>{m.email}</td><td>{m.name}</td><td>{m.status}</td></tr>)}</tbody></table>{more && <button onClick={() => void loadMembers(listId, members.at(-1)?.id)}>Load more subscribers</button>}</div>}
  </div>;
}
